extends Node
## Global signal hub so systems and UI stay decoupled.

signal time_changed(minute: int)
signal day_started(day_index: int, report: Dictionary)
signal day_ending()
signal money_changed(money: int, delta: int)
signal inventory_changed()
signal hotbar_changed()
signal energy_changed(energy: float, max_energy: float)
signal party_changed()
signal toast(text: String, icon: String)
## Farm Story style floating reward: world position, text, color.
signal popup(world_pos: Vector2, text: String, color: Color)
signal farm_level_up(level: int, info: Dictionary)
signal dialogue_requested(speaker: String, lines: Array, portrait: String)
signal choice_requested(prompt: String, options: Array, callback: Callable)
signal battle_requested(setup: Dictionary)
signal battle_finished(result: Dictionary)
signal map_change_requested(map_id: String, tile: Vector2i)
signal map_changed(map_id: String)
signal menu_requested(menu: String, args: Dictionary)
signal menu_closed(menu: String)
signal tile_changed(map_id: String, tile: Vector2i)
signal objects_changed(map_id: String)
signal weather_changed(weather: String)
signal creature_befriended(creature: Creature)
signal egg_hatched(creature: Creature)
signal quest_updated()
signal net_status(text: String)
signal shake(strength: float)
